/**
 * DON'T EDIT THIS FILE WHICH WAS GENERATED BY './scripts/generate-configs.js'.
 */
"use strict"

module.exports = {
    all: require("./configs/all"),
    es2015: require("./configs/es2015"),
    es5: require("./configs/es5"),
}
