/**
 * DON'T EDIT THIS FILE WHICH WAS GENERATED BY './scripts/generate-configs.js'.
 */
"use strict"

module.exports = {
    "+browser": require("./configs/+browser"),
    "+eslint-plugin": require("./configs/+eslint-plugin"),
    "+modules": require("./configs/+modules"),
    "+node": require("./configs/+node"),
    es2015: require("./configs/es2015"),
    es2016: require("./configs/es2016"),
    es2017: require("./configs/es2017"),
    es2018: require("./configs/es2018"),
    es2019: require("./configs/es2019"),
    es2020: require("./configs/es2020"),
    es2021: require("./configs/es2021"),
    es5: require("./configs/es5"),
}
