/**
 * DON'T EDIT THIS FILE WHICH WAS GENERATED BY './scripts/generate-rules.js'.
 */
"use strict"

module.exports = Object.assign(
    require("./foreign-rules/eslint-comments"),
    require("./foreign-rules/eslint-plugin"),
    require("./foreign-rules/node"),
    require("./foreign-rules/prettier"),
    require("./foreign-rules/ts"),
    require("./foreign-rules/vue"),
    {
        "arrow-parens": require("./rules/arrow-parens"),
        "block-scoped-var": require("./rules/block-scoped-var"),
        "no-instanceof-array": require("./rules/no-instanceof-array"),
        "no-instanceof-wrapper": require("./rules/no-instanceof-wrapper"),
        "no-literal-call": require("./rules/no-literal-call"),
        "no-this-in-static": require("./rules/no-this-in-static"),
        "no-use-ignored-vars": require("./rules/no-use-ignored-vars"),
        "no-useless-rest-spread": require("./rules/no-useless-rest-spread"),
        "prefer-for-of": require("./rules/prefer-for-of"),
    }
)
